# ---------- BUILD ----------
FROM node:20-alpine AS builder

RUN apk add --no-cache python3 make g++

WORKDIR /app

COPY package*.json ./
COPY prisma ./prisma/

RUN npm ci

RUN npx prisma generate

COPY . .

RUN npm run build


# ---------- PRODUCTION ----------
FROM node:20-alpine

WORKDIR /app

RUN apk add --no-cache bash python3

# Instalar ts-node globalmente para el seed
RUN npm install -g ts-node

COPY --from=builder /app/dist /app/dist
COPY --from=builder /app/node_modules /app/node_modules
COPY --from=builder /app/package*.json /app/
COPY --from=builder /app/prisma /app/prisma

RUN mkdir -p /app/data && chmod 777 /app/data

EXPOSE 3001

CMD sh -c "npx prisma migrate deploy && node dist/src/main.js"